/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#include "calc.h"

START_TEST(TEST_ERROR_RES) {
  bool is_error = false;

  ck_assert_double_eq(smart_calc("8+5.5.57^-1", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("-5^--1", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("-5*--1", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("*7+8", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("*7+(8-)", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("-+3mod4^7", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("+3mod4^7---9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(+3mod4^7---9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("+3mod4^7)---9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(+3mod4^7))---9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(+3mod4^7-)--9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(3w4^7)-9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(*3^7)", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(3^7)6", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("5(3^7)", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(3^7)*()", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(3.876.87+6", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("(3.+6", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);

  ck_assert_double_eq(smart_calc("cos5+9", &is_error, 0), 0.);
  ck_assert_int_eq(is_error, 1);
}
END_TEST

START_TEST(TEST_TRUE_RES) {
  bool is_error = false;

  ck_assert_double_eq(smart_calc("2-20/4", &is_error, 0), -3.00000000);
  ck_assert_double_nan(
      smart_calc("+7.6*-(+2.8--8.5-(-6.5^-4.8^+1.5))", &is_error, 0));
  ck_assert_double_eq(smart_calc("2--(4+9)", &is_error, 0), 15.00000000);
  ck_assert_double_eq(smart_calc("4*(-(5+9))", &is_error, 0), -56.00000000);
  ck_assert_double_eq(smart_calc("4*(-(-(5+9)))", &is_error, 0), 56.00000000);
  ck_assert_double_eq(smart_calc("-4/0+8", &is_error, 0), -INFINITY);
  ck_assert_double_eq(smart_calc("-4/-0+8", &is_error, 0), INFINITY);
  ck_assert_double_eq(smart_calc("4/-0+8", &is_error, 0), -INFINITY);
  ck_assert_double_eq(smart_calc("4/0+8", &is_error, 0), INFINITY);
  ck_assert_double_nan(
      smart_calc("+7.6*(+2.8-8.5-(6.5^-4.8^1.5))", &is_error, 0));
  ck_assert_double_eq_tol(
      smart_calc("+7.6*(+2.8-8.5-(6.5^4.8^1.5))", &is_error, 0),
      -2689257990.49688196, EPS);
  ck_assert_double_eq_tol(smart_calc("7.6*(2.8-8.5-(6.5^4.8))", &is_error, 0),
                          -60688.69755735, EPS);
  ck_assert_double_eq_tol(smart_calc("2/-3mod4", &is_error, 0), -0.66666667,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("2/-3^4", &is_error, 0), 0.02469136, EPS);
  ck_assert_double_eq_tol(smart_calc("-2^-3^2", &is_error, 0), -512.00000000,
                          EPS);
  ck_assert_double_nan(smart_calc("-2^-3^-2", &is_error, 0));
  ck_assert_double_eq(smart_calc("2^3^2", &is_error, 0), 512.00000000);
  ck_assert_double_eq(smart_calc("10mod6mod3", &is_error, 0), 1.00000000);
  ck_assert_double_nan(smart_calc("-2^3.2", &is_error, 0));
  ck_assert_double_eq_tol(smart_calc("2/-3^4*2", &is_error, 0), 0.04938272,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("+2/-3^4*-2", &is_error, 0), -0.04938272,
                          EPS);
  ck_assert_double_eq(smart_calc("-(10/5+4-9)^3", &is_error, 0), 27.00000000);
  ck_assert_double_eq(smart_calc("+2-173.7/-3^4^78^4*-2", &is_error, 0),
                      2.00000000);
  ck_assert_double_eq(smart_calc("-3^4^78^4", &is_error, 0), INFINITY);
  ck_assert_double_eq(smart_calc("173.7/-3^4^78^4", &is_error, 0), 0.00000000);
  ck_assert_double_eq(smart_calc("+3/4*7", &is_error, 0), 5.25000000);
  ck_assert_double_eq(smart_calc("+3^4mod7", &is_error, 0), 4.00000000);
  ck_assert_double_eq(smart_calc("+3mod5mod6^4mod7", &is_error, 0), 3.00000000);
  ck_assert_double_eq(smart_calc("+3mod4^7", &is_error, 0), 3.00000000);
  ck_assert_double_eq(smart_calc("+3mod4^7++9", &is_error, 0), 12.00000000);
  ck_assert_double_eq(smart_calc("4*(-(5+9))", &is_error, 0), -56.00000000);
  ck_assert_double_eq(smart_calc("4*-(5+9)", &is_error, 0), -56.00000000);
  ck_assert_double_eq_tol(smart_calc("2^-(5/2-1)", &is_error, 0), 0.35355339,
                          EPS);
  ck_assert_double_eq(smart_calc("-(5+9)", &is_error, 0), -14.00000000);
}
END_TEST

START_TEST(TEST_SIN) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("sin(-1)", &is_error, 0), -0.84147098,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("sin(0)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("sin(1)", &is_error, 0), 0.84147098, EPS);
  ck_assert_double_eq_tol(smart_calc("sin(4+6*2)", &is_error, 0), -0.28790332,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("sin(4+3^2)", &is_error, 0), 0.42016704,
                          EPS);
}
END_TEST

START_TEST(TEST_COS) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("cos(-1)", &is_error, 0), 0.54030231, EPS);
  ck_assert_double_eq_tol(smart_calc("cos(0)", &is_error, 0), 1.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("cos(1)", &is_error, 0), 0.54030231, EPS);
  ck_assert_double_eq_tol(smart_calc("cos(4+6*2)", &is_error, 0), -0.95765948,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("cos(4+3^2)", &is_error, 0), 0.90744678,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("cos(43--4*cos(5)^2)", &is_error, 0),
                          0.78972226, EPS);
  ck_assert_double_eq_tol(smart_calc("-cos(43--4*cos(5)^2)", &is_error, 0),
                          -0.78972226, EPS);
}
END_TEST

START_TEST(TEST_TAN) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("tan(-1)", &is_error, 0), -1.55740772,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("tan(0)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("tan(1)", &is_error, 0), 1.55740772, EPS);
  ck_assert_double_eq_tol(smart_calc("tan(4+6*2)", &is_error, 0), 0.30063224,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("tan(4+3^2)", &is_error, 0), 0.46302113,
                          EPS);
}
END_TEST

START_TEST(TEST_ASIN) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("asin(-1)", &is_error, 0), -1.57079633,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("asin(0)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("asin(1)", &is_error, 0), 1.57079633, EPS);
  ck_assert_double_nan(smart_calc("asin(4+6*2)", &is_error, 0));
  ck_assert_double_nan(smart_calc("asin(4+3^2)", &is_error, 0));
}
END_TEST

START_TEST(TEST_ACOS) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("acos(-1)", &is_error, 0), 3.14159265,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("acos(0)", &is_error, 0), 1.57079633, EPS);
  ck_assert_double_eq_tol(smart_calc("acos(1)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_nan(smart_calc("acos(4+6*2)", &is_error, 0));
  ck_assert_double_nan(smart_calc("acos(4+3^2)", &is_error, 0));
}
END_TEST

START_TEST(TEST_ATAN) {
  bool is_error = false;

  ck_assert_double_eq_tol(smart_calc("atan(-1)", &is_error, 0), -0.78539816,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("atan(0)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("atan(1)", &is_error, 0), 0.78539816, EPS);
  ck_assert_double_eq_tol(smart_calc("atan(4+6*2)", &is_error, 0), 1.50837752,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("atan(4+3^2)", &is_error, 0), 1.49402444,
                          EPS);
}
END_TEST

START_TEST(TEST_SQRT) {
  bool is_error = false;

  ck_assert_double_nan(smart_calc("sqrt(-1)", &is_error, 0));
  ck_assert_double_eq_tol(smart_calc("sqrt(0)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("sqrt(1)", &is_error, 0), 1.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("sqrt(4+6*2)", &is_error, 0), 4.00000000,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("sqrt(4+3^2)", &is_error, 0), 3.60555128,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("sqrt(4^2)", &is_error, 0), 4.00000000,
                          EPS);
}
END_TEST

START_TEST(TEST_LN) {
  bool is_error = false;

  ck_assert_double_nan(smart_calc("ln(-1)", &is_error, 0));
  ck_assert_double_eq(smart_calc("ln(0)", &is_error, 0), -INFINITY);
  ck_assert_double_eq_tol(smart_calc("ln(1)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("ln(4+6*2)", &is_error, 0), 2.77258872,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("ln(4+3^2)", &is_error, 0), 2.56494936,
                          EPS);
}
END_TEST

START_TEST(TEST_LOG) {
  bool is_error = false;

  ck_assert_double_nan(smart_calc("log(-1)", &is_error, 0));
  ck_assert_double_eq(smart_calc("log(0)", &is_error, 0), -INFINITY);
  ck_assert_double_eq_tol(smart_calc("log(1)", &is_error, 0), 0.00000000, EPS);
  ck_assert_double_eq_tol(smart_calc("log(4+6*2)", &is_error, 0), 1.20411998,
                          EPS);
  ck_assert_double_eq_tol(smart_calc("log(4+3^2)", &is_error, 0), 1.11394335,
                          EPS);
}
END_TEST

START_TEST(TEST_X) {
  bool is_error = false;

  ck_assert_double_eq(smart_calc("x+2", &is_error, 5.5), 7.50000000);
  ck_assert_double_eq(smart_calc("x^2", &is_error, 2), 4.00000000);
  ck_assert_double_eq(smart_calc("x*3", &is_error, 1.25), 3.75000000);
  ck_assert_double_eq(smart_calc("2^3^x", &is_error, 2), 512.00000000);
}
END_TEST

int main(void) {
  Suite* s1 = suite_create("Core");
  TCase* tc1_1 = tcase_create("Core");
  SRunner* sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, TEST_ERROR_RES);
  tcase_add_test(tc1_1, TEST_TRUE_RES);
  tcase_add_test(tc1_1, TEST_SIN);
  tcase_add_test(tc1_1, TEST_COS);
  tcase_add_test(tc1_1, TEST_TAN);
  tcase_add_test(tc1_1, TEST_ASIN);
  tcase_add_test(tc1_1, TEST_ACOS);
  tcase_add_test(tc1_1, TEST_ATAN);
  tcase_add_test(tc1_1, TEST_SQRT);
  tcase_add_test(tc1_1, TEST_LN);
  tcase_add_test(tc1_1, TEST_LOG);
  tcase_add_test(tc1_1, TEST_X);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
